"""#653 — P1 of the #630 component transition: the build step, and the two
things that make a committed build artifact safe.

The claim of this phase is small and checkable: **`just build-client` exists,
`client/dist/` is committed, and the served page does not change by one byte.**
Measured at the landing — before 601928 bytes / sha256 ceecce6853f2689d3…, after
the same — but a recorded hash is no use afterwards, because every legitimate
UI edit changes it. So what this file pins instead is the property that made
the number true and must stay true: **nothing under client/dist reaches PAGE**.

The other half is staleness. dist is committed (deploy ships committed state,
`justfile:418-423`, and the dashboard must come up with no node), so it can be
built from bytes that are no longer here. That cannot be made *impossible*
without a serve-time build, which the no-node requirement refuses — so it is
made impossible to MISS, and these checks are what say so.

Two rules from #397 govern every check below, and both are about checks that
pass for the wrong reason:

  1. **Every comparison asserts its own preconditions.** A byte-comparison
     passes vacuously on two empty sides; a containment check passes when the
     thing it looks for was never there to find. Each floor here is derived at
     runtime from the tree being measured, never a literal tuned to today's.
  2. **Every detector is proved able to detect.** Each red-proof below is a
     test, not a ceremony — and where the obvious red-proof would still admit
     a broken input, the test for THAT input is written too (the manifest that
     records nine hashes that all match while the tenth file is missing; the
     asset list that is reordered without one byte changing).
"""

import json
import os
import pathlib
import shutil
import subprocess

import pytest

import client_dist
import watch

ROOT = pathlib.Path(__file__).resolve().parent
CLIENT = ROOT / "client"


def _clone(tmp_path):
    """A whole checkout's worth of the build's subject, in tmp_path.

    The red-proofs mutate build inputs and manifests. They do it HERE, never
    in the repo: `client_dist.check` takes a root precisely so a proof cannot
    reach the tree it is run from. (`lessons.md:757` — the #348 incident that
    #349 tracks — sharpened by #652, where a lane found ANOTHER lane's
    snapshot in the shared scratchpad. The safest snapshot is the one that
    never has to be taken.)
    """
    dst = tmp_path / "root"
    dst.mkdir()
    shutil.copy(ROOT / "watch.py", dst / "watch.py")
    shutil.copytree(CLIENT, dst / "client")
    wrap = dst / client_dist.WRAPPER_EXPORTS_REL
    wrap.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy(ROOT / client_dist.WRAPPER_EXPORTS_REL, wrap)
    # The clone must start CLEAN, or every proof below could be reading a
    # defect the clone introduced rather than the one it injected.
    reading = client_dist.check(str(dst))
    assert reading["state"] == client_dist.OK, (
        "the fixture clone is not a faithful copy — %r; every injection below "
        "would then be proving nothing" % (reading,))
    return dst


def _manifest(root):
    with open(os.path.join(str(root), client_dist.MANIFEST_REL),
              encoding="utf-8") as f:
        return json.load(f)


def _write_manifest(root, obj):
    with open(os.path.join(str(root), client_dist.MANIFEST_REL), "w",
              encoding="utf-8") as f:
        json.dump(obj, f, indent=2, sort_keys=True)
        f.write("\n")


# ── the phase's own claim ────────────────────────────────────────────────


def test_nothing_under_client_dist_reaches_the_assembled_page():
    """P1's whole promise, as a property rather than a recorded hash.

    The page was byte-identical across this landing. That measurement cannot
    be re-run tomorrow (any UI edit moves it), but the REASON it held can be:
    the build emits into client/dist and the page is assembled from
    client/*.js, and the two sets do not meet.

    Non-vacuous by construction: each probe string is asserted PRESENT in the
    built bundle first. A check that looks in the page for something that does
    not exist anywhere passes forever and means nothing — which is exactly how
    a containment check goes false-green.
    """
    index = (ROOT / client_dist.DS_DIR / "index.js").read_bytes().decode("utf-8")
    assert len(index) > 1000, (
        "client/dist/ds/index.js is %d chars — too small to be a bundle, and "
        "every probe below would be looking for nothing" % len(index))

    # Strings that exist ONLY in build output: the generated banner, esbuild's
    # entry marker, and the package's global name.
    probes = ["GENERATED by `just build-client`", "// entry.mjs",
              "DreamworkDesign"]
    for probe in probes:
        assert probe in index, (
            "%r is not in the built bundle, so its absence from the page "
            "would prove nothing" % probe)

    page = watch._get_page()
    floor = sum((CLIENT / n).stat().st_size for n in watch._CLIENT_ASSETS)
    assert floor > 0, "no client assets to derive a floor from"
    assert len(page) > floor, (
        "the assembled page is %d chars against %d chars of client assets — "
        "an asset is missing from the page, so this is not the dashboard and "
        "the containment checks below are meaningless" % (len(page), floor))

    for probe in probes:
        assert probe not in page, (
            "%r reached the served page — client/dist is P1's build output "
            "and nothing in it may be served yet; the byte-identity claim of "
            "this phase is false" % probe)


def test_ds_styles_is_a_byte_copy_of_the_stylesheet_the_page_serves():
    """The design package ships the dashboard's own stylesheet, not a fork.

    A second, editable copy of the visual language is a second authority for
    it — the thing Q1 refuses. So it is a copy, and this is what keeps it one.

    Precondition derived at runtime: both sides must carry the first custom
    property client/style.css actually declares. Two empty files are
    byte-equal, and a check that cannot tell that case from success is not a
    check.
    """
    served = (CLIENT / "style.css").read_bytes()
    shipped = (ROOT / client_dist.DS_DIR / "styles.css").read_bytes()
    text = served.decode("utf-8")
    tokens = [ln.split(":")[0].strip() for ln in text.splitlines()
              if ln.strip().startswith("--") and ":" in ln]
    assert tokens, (
        "client/style.css declares no custom property, so this test has no "
        "runtime-derived sentinel and would pass on two empty files")
    token = tokens[0]
    assert token.encode() in served and token.encode() in shipped, (
        "%s is not in both stylesheets — the comparison below could be "
        "comparing two blanks" % token)
    assert served == shipped, (
        "client/dist/ds/styles.css has drifted from client/style.css — the "
        "design package would ship a stylesheet the dashboard does not use")


def test_wrapper_exports_states_no_markup_of_its_own():
    """#630 §2b's "no restatement", enforced rather than reviewed.

    The one hand-written build input may CALL a builder; it may never restate
    its markup, because a second statement is the only place divergence could
    live. Today the file exports nothing, so this passes trivially — and that
    is the point of landing it now: the rule is in place before the first
    wrapper is written, not argued about afterwards.

    The detector proves itself first: it must find tag literals in
    client/components.js, which is FULL of them. A regex that had stopped
    matching anything would otherwise clear this file forever.
    """
    import re
    tag = re.compile(r"<\s*/?\s*(div|span|a|button|p|ul|li|table|tr|td|h[1-6]|"
                     r"section|header|footer|input|textarea|form|img|svg)\b",
                     re.I)
    builders = (CLIENT / "components.js").read_text(encoding="utf-8")
    found = tag.findall(builders)
    assert len(found) > 20, (
        "the tag-literal detector found %d tags in client/components.js, "
        "which is built entirely out of them — the detector is broken, and a "
        "broken detector clears the file below by finding nothing"
        % len(found))

    wrapper = (ROOT / client_dist.WRAPPER_EXPORTS_REL).read_text(
        encoding="utf-8")
    # comments are prose about the rule, not markup subject to it
    code = "\n".join(ln for ln in wrapper.splitlines()
                     if not ln.lstrip().startswith(("//", "*", "/*")))
    hits = tag.findall(code)
    assert not hits, (
        "%s states markup of its own (%r). A wrapper must CALL the builder — "
        "a second statement of the same markup is the one thing that can "
        "diverge from it" % (client_dist.WRAPPER_EXPORTS_REL, sorted(set(hits))))


# ── the staleness detector, and the ways it could pass while wrong ───────


def test_the_committed_dist_is_built_from_the_committed_tree():
    """The standing check, in pytest as well as in lint.

    Its own precondition first: the input set must be the whole asset list
    plus the hand-written file. A check over an empty input set is green
    forever.
    """
    want = client_dist.expected_inputs(str(ROOT))
    assert want is not None, "watch._CLIENT_ASSETS is not AST-readable"
    assert len(want) == len(watch._CLIENT_ASSETS) + 1, (
        "expected %d inputs, derived %d" % (len(watch._CLIENT_ASSETS) + 1,
                                            len(want)))
    reading = client_dist.check(str(ROOT))
    assert reading["state"] == client_dist.OK, (
        "client/dist is %s: %s — run `just build-client`"
        % (reading["state"], reading["note"]))


def test_an_edited_input_reds_the_detector(tmp_path):
    """RED PROOF, the plain direction: touch one byte of a builder.

    This is the defect the whole mechanism exists for — a design bundle
    compiled from yesterday's `components.js`.
    """
    root = _clone(tmp_path)
    target = root / "client" / "components.js"
    raw = target.read_bytes()
    target.write_bytes(raw + b"\n// one byte of drift\n")

    reading = client_dist.check(str(root))
    assert reading["state"] == client_dist.STALE, (
        "an edited builder did not read as stale (%r) — every client edit "
        "from here on would ship a dist built from something else"
        % (reading,))
    assert any("components.js" in s for s in reading["stale"]), (
        "the reading does not NAME the file that drifted: %r" % (reading,))
    assert reading["fix"], "a red with no fix named is a red nobody can clear"


def test_an_edited_output_reds_the_detector(tmp_path):
    """RED PROOF: the other side of the manifest. A hand-edited artifact is
    the temptation a committed build creates — the file is right there."""
    root = _clone(tmp_path)
    out = root / client_dist.DS_DIR / "index.js"
    out.write_bytes(out.read_bytes() + b"\n/* hand-edited */\n")
    reading = client_dist.check(str(root))
    assert reading["state"] == client_dist.STALE, (
        "a hand-edited build artifact read as %r" % (reading["state"],))
    assert any("index.js" in s for s in reading["stale"]), reading


def test_a_manifest_that_forgot_an_input_is_stale_though_every_hash_matches(
        tmp_path):
    """FALSE-GREEN VECTOR, closed.

    Construct the input that is genuinely broken but that the obvious check
    passes on: drop one asset from the manifest's `inputs` map and change
    nothing else. Every hash the manifest still records matches its file
    exactly, so a detector that iterates the MANIFEST's keys reports green —
    while the dist was in fact built without that asset.

    This is the shape a real ninth asset would take: someone adds
    `client/foo.js` to `_CLIENT_ASSETS`, never rebuilds, and the manifest
    simply does not mention it. The check must derive its key set from the
    TREE, which is why `expected_inputs` reads `_CLIENT_ASSETS` rather than
    the manifest.
    """
    root = _clone(tmp_path)
    manifest = _manifest(root)
    dropped = "client/components.js"
    assert dropped in manifest["inputs"], "fixture assumption broken"
    del manifest["inputs"][dropped]
    _write_manifest(root, manifest)

    # the vector is real: every hash still recorded is still correct, so a
    # manifest-keyed detector has nothing to report.
    for rel, digest in manifest["inputs"].items():
        assert client_dist.sha256_file(os.path.join(str(root), rel)) == digest, (
            "the injection changed a file it should not have; the false-green "
            "it is demonstrating would not be demonstrated")

    reading = client_dist.check(str(root))
    assert reading["state"] == client_dist.STALE, (
        "a dist built without client/components.js read as %r — the detector "
        "is trusting the manifest's own key set" % (reading["state"],))
    assert dropped in reading["note"], reading


def test_a_reordered_asset_list_is_stale_though_no_byte_changed(tmp_path):
    """FALSE-GREEN VECTOR, closed.

    The page concatenates the assets in `_CLIENT_ASSETS` order, and the bundle
    is generated in that same order. Swap two entries and every file on disk is
    byte-identical — so a hash-only detector, over the correct key set, is
    still green, while the bundle now means something different from the page.

    Order is an input. This is the check that says so.
    """
    root = _clone(tmp_path)
    src = (root / "watch.py").read_text(encoding="utf-8")
    order = client_dist.asset_order(str(root))
    a, b = order[2], order[3]
    assert a.endswith(".js") and b.endswith(".js"), (
        "fixture wants two JS assets to swap, got %r/%r" % (a, b))
    swapped = src.replace('    "%s",\n    "%s",\n' % (a, b),
                          '    "%s",\n    "%s",\n' % (b, a), 1)
    assert swapped != src, "the asset-list swap did not apply"
    (root / "watch.py").write_text(swapped, encoding="utf-8")
    assert client_dist.asset_order(str(root))[2:4] == [b, a], (
        "the swap did not change what the AST reads — nothing was injected")

    # every hash is still correct; only the ORDER moved.
    manifest = _manifest(root)
    for rel, digest in list(manifest["inputs"].items()) + \
            list(manifest["outputs"].items()):
        assert client_dist.sha256_file(os.path.join(str(root), rel)) == digest

    reading = client_dist.check(str(root))
    assert reading["state"] == client_dist.STALE, (
        "reordering the page's assets left dist reading %r — the bundle would "
        "silently disagree with the page about load order"
        % (reading["state"],))


def test_an_empty_manifest_does_not_pass_by_having_nothing_to_compare(
        tmp_path):
    """FALSE-GREEN VECTOR, closed: the vacuous manifest.

    `{"inputs": {}, "outputs": {}}` satisfies every hash comparison there is,
    by supplying none. This is the shape a half-written or truncated manifest
    takes, and it must not read as a clean build.
    """
    root = _clone(tmp_path)
    _write_manifest(root, {"schema": client_dist.SCHEMA, "tool": {},
                           "asset_order": client_dist.asset_order(str(root)),
                           "inputs": {}, "outputs": {}})
    reading = client_dist.check(str(root))
    assert reading["state"] != client_dist.OK, (
        "a manifest recording nothing read as a current build")


def test_a_manifest_with_inputs_but_no_outputs_is_not_clean(tmp_path):
    """The same vacuity one level in: recording every input correctly while
    claiming no outputs would leave the artifact half of the check with
    nothing to iterate."""
    root = _clone(tmp_path)
    manifest = _manifest(root)
    manifest["outputs"] = {}
    _write_manifest(root, manifest)
    assert client_dist.check(str(root))["state"] != client_dist.OK


# ── the states where the check's own subjects are absent ─────────────────


def test_a_missing_manifest_is_a_named_state_and_never_a_raise(tmp_path):
    """lessons.md:580 / :622 — a guard assertion whose subject may not exist
    must RETURN a reading, never throw. The absent case is precisely the one
    this check was written for; a traceback there reads like the check being
    broken and starts the diagnosis in the wrong place."""
    root = _clone(tmp_path)
    os.remove(os.path.join(str(root), client_dist.MANIFEST_REL))
    reading = client_dist.check(str(root))          # must not raise
    assert reading["state"] == client_dist.MISSING, reading
    assert client_dist.MANIFEST_REL in reading["note"], reading


def test_an_unparseable_manifest_is_a_named_state_and_never_a_raise(tmp_path):
    root = _clone(tmp_path)
    with open(os.path.join(str(root), client_dist.MANIFEST_REL), "w") as f:
        f.write("{ this is not json")
    reading = client_dist.check(str(root))          # must not raise
    assert reading["state"] in (client_dist.MISSING, client_dist.UNREADABLE)
    assert reading["state"] != client_dist.OK


def test_an_unreadable_watch_py_reports_rather_than_crashing(tmp_path):
    """The input set is derived from watch.py by AST. If that read fails the
    check knows nothing — and must SAY so, not pass and not explode."""
    root = _clone(tmp_path)
    (root / "watch.py").write_text("def (: not python\n", encoding="utf-8")
    reading = client_dist.check(str(root))          # must not raise
    assert reading["state"] == client_dist.UNREADABLE, reading


def test_a_missing_input_file_is_stale_not_a_crash(tmp_path):
    root = _clone(tmp_path)
    os.remove(str(root / "client" / "shader.js"))
    reading = client_dist.check(str(root))          # must not raise
    assert reading["state"] == client_dist.STALE, reading
    assert any("shader.js" in s for s in reading["stale"]), reading


def test_serving_report_carries_the_dist_reading_on_its_EARLY_return(tmp_path):
    """The serving-time surface, checked where it is most likely to be lost.

    `serving_report` has several early returns — a target that is not a git
    checkout leaves on the first one. A reading attached at the bottom of the
    happy path would be absent from exactly those answers, which is the
    "a comparison that could not run must not look like one that ran and found
    nothing" rule the function's own docstring states, one field over.

    The precondition is the point: assert the git half really did bail early,
    or this passes on the ordinary path and proves nothing about the others.
    """
    rep = watch.serving_report(str(tmp_path))       # an empty dir, no .git
    assert rep["state"] == watch.SERVE_NOREPO, (
        "fixture did not take the early return (%r), so this says nothing "
        "about whether the reading survives one" % rep["state"])
    assert "client_dist" in rep, (
        "serving_report dropped the client/dist reading on its early return — "
        "the serving-time half of the staleness signal is missing exactly "
        "where the rest of the report could not be computed")
    assert rep["client_dist"]["state"] == client_dist.OK, rep["client_dist"]


# ── shipping: the half that has bricked the dashboard twice ──────────────


def test_deploy_declares_and_tracks_every_file_the_dist_check_reads(tmp_path):
    """#425/#480 — `just deploy` ships DATA_SIBLINGS, and it TREE-FILTERS at
    the rev (`dev/deploy_state.py:374`). So a path that is declared but
    untracked is dropped in silence: the deployed instance would simply not
    have it, and the staleness reading there would be red forever with no
    edit to explain it.

    Two assertions, because declaring and tracking fail differently and both
    fail quietly.
    """
    declared = set(watch.DATA_SIBLINGS)
    want = ([client_dist.MANIFEST_REL, client_dist.WRAPPER_EXPORTS_REL]
            + list(client_dist.OUTPUT_RELS))
    missing = sorted(p for p in want if p not in declared)
    assert not missing, (
        "DATA_SIBLINGS does not declare %r — deploy would ship a snapshot "
        "whose client/dist check can never come back clean" % missing)

    for rel in want:
        assert (ROOT / rel).is_file(), "%s is declared but not on disk" % rel
        res = subprocess.run(
            ["git", "--no-optional-locks", "-C", str(ROOT), "ls-files",
             "--error-unmatch", "--", rel],
            capture_output=True)
        assert res.returncode == 0, (
            "%s is not tracked by git. deploy ships COMMITTED state and "
            "tree-filters DATA_SIBLINGS at the rev, so an untracked entry is "
            "discarded without a word" % rel)


def test_deploy_stages_the_dist_subdirectory_for_real(tmp_path):
    """Not "the tuple looks right" — actually run the shipper.

    `client/dist/ds/` is the first two-deep data sibling in this repo, and the
    belief that `ship_siblings` makes parent directories is exactly the kind of
    belief that has bricked this dashboard twice. Verified against a scratch
    destination; never against the live deployment.

    Shipped from the INDEX tree, not `HEAD`, and the difference is the whole
    finding. Written against HEAD this went red on its first run — deploy
    tree-filters at the rev (`deploy_state.py:374`), so a path that is not
    in the rev is discarded without a word, which is precisely the silent drop
    the test exists to catch. Against HEAD it could also never go green in the
    commit that first adds dist, and a check that cannot pass until after the
    thing it gates has landed gates nothing. The index is what is about to
    become HEAD; in any committed checkout the two trees agree.
    """
    import sys
    sys.path.insert(0, str(ROOT / "dev"))
    import deploy_state

    res = subprocess.run(
        ["git", "--no-optional-locks", "-C", str(ROOT), "write-tree"],
        capture_output=True, text=True)
    assert res.returncode == 0, (
        "cannot read the index as a tree: %s" % res.stderr.strip())
    rev = res.stdout.strip()
    assert rev, "git write-tree produced no object"
    # Precondition: the tree being shipped must actually carry the files, or
    # the shipper would be asked to move nothing and this would fail for a
    # reason that has nothing to do with subdirectories.
    listing = subprocess.run(
        ["git", "--no-optional-locks", "-C", str(ROOT), "ls-tree", "-r",
         "--name-only", rev, "--", client_dist.DIST_DIR],
        capture_output=True, text=True).stdout.split()
    assert client_dist.MANIFEST_REL in listing, (
        "%s is not in the index — stage it before this can say anything"
        % client_dist.MANIFEST_REL)

    dest = tmp_path / "snap"
    dest.mkdir()
    written = deploy_state.ship_siblings(rev, str(dest), repo=ROOT)
    assert written, "ship_siblings staged nothing at all"
    for rel in [client_dist.MANIFEST_REL] + list(client_dist.OUTPUT_RELS):
        staged = dest / rel
        assert staged.is_file(), (
            "%s was not staged into the deploy snapshot — the deployed "
            "dashboard would not carry it" % rel)
        assert staged.read_bytes() == (ROOT / rel).read_bytes(), (
            "%s shipped with different bytes than the tree holds" % rel)


def test_autoreload_sees_a_rebuild(tmp_path):
    """`just build-client` must clear the startup red without a manual restart.

    The WARNING is read once per process, so a dev who rebuilds to fix a red
    would keep seeing the red until they restarted by hand — #397's
    "edit and see nothing" loop, one layer out.
    """
    watched = set(watch._autoreload_sources())
    for rel in (client_dist.MANIFEST_REL,) + client_dist.OUTPUT_RELS:
        assert os.path.join(watch.SELF_DIR, rel) in watched, (
            "%s is not in the autoreload watch set" % rel)
    assert all(os.path.isabs(p) for p in watched), (
        "relative paths in the watch set survive until someone chdirs, and "
        "_sources_mtime's OSError handling would then hide that a file had "
        "stopped being watched at all")


def test_derived_output_is_not_counted_as_a_presentation_change():
    """`client/dist/` is under `client/`, and the styleguide audit classifies
    a commit as UI by that prefix — so without an exclusion every rebuild
    would demand a styleguide entry for a file nobody authored.

    Both directions asserted: a real asset must still classify as UI, or this
    would pass on a predicate that had stopped recognising anything.
    """
    import sys
    sys.path.insert(0, str(ROOT / "dev"))
    import styleguide_audit

    for rel in ("client/style.css", "client/components.js"):
        assert styleguide_audit.is_ui_asset(rel), (
            "%s stopped classifying as a UI asset — the audit would go green "
            "over real presentation changes" % rel)
    for rel in [client_dist.MANIFEST_REL] + list(client_dist.OUTPUT_RELS):
        assert not styleguide_audit.is_ui_asset(rel), (
            "%s classifies as a presentation change; a rebuild would demand "
            "a styleguide entry for generated output" % rel)


# ── the build itself ─────────────────────────────────────────────────────


def _esbuild():
    path = ROOT / "dev" / "build" / "node_modules" / ".bin" / "esbuild"
    return path if path.exists() else None


def test_the_build_is_reproducible_and_the_committed_output_is_its_output(
        tmp_path):
    """Rebuild from a clean clone; the bytes must match what is committed.

    This is the check that caught the design's one real defect: esbuild writes
    the entry file's path into the bundle as a comment, and building from a
    randomly-named temp directory made every rebuild emit a different artifact.
    A committed artifact that changes on a no-op rebuild makes its own hash
    manifest churn — and a staleness signal that fires when nothing is stale
    is the false red that trains you to ignore the real one (lessons.md:157).
    Production line: `cwd=tmp` with a relative entry name in
    `dev/build_client.py`. Pass the absolute path instead and this goes red.
    """
    if _esbuild() is None:
        pytest.skip("dev/build/node_modules absent — `just build-client` "
                    "installs it; the reading this check needs is the "
                    "toolchain's own output")
    import sys
    sys.path.insert(0, str(ROOT / "dev"))
    import build_client

    root = _clone(tmp_path)
    manifest = build_client.build(str(root))
    assert manifest["outputs"], "the build recorded no outputs"
    for rel, digest in manifest["outputs"].items():
        committed = client_dist.sha256_file(str(ROOT / rel))
        assert committed is not None, "%s is not committed" % rel
        assert digest == committed, (
            "rebuilding %s produced different bytes than the committed "
            "artifact — either the build is not reproducible, or dist is "
            "stale and `just build-client` was not run" % rel)


def test_the_build_refuses_an_empty_asset_rather_than_bundling_a_blank(
        tmp_path):
    """The `_read_client` discipline (`watch.py:497`), one layer out: an empty
    input bundles to a valid, silent nothing, and the manifest would then
    faithfully record the hash of a blank."""
    if _esbuild() is None:
        pytest.skip("dev/build/node_modules absent")
    import sys
    sys.path.insert(0, str(ROOT / "dev"))
    import build_client

    root = _clone(tmp_path)
    (root / "client" / "shader.js").write_bytes(b"")
    with pytest.raises(build_client.BuildError) as exc:
        build_client.build(str(root))
    assert "shader.js" in str(exc.value), (
        "the refusal does not name the empty asset: %s" % exc.value)
