"""#653 — `just build-client`: emit `client/dist/` from the tree, and record
exactly which tree it was.

This is P1 of the #630 component transition: the build step, emitting nothing
the page uses. The dashboard is byte-identical with and without it — that is
the whole claim of this phase, and it is checked in `test_client_dist.py`
rather than argued.

Two properties are built in here rather than left to care:

**The entry is GENERATED, never maintained.** `watch.py` concatenates the
client assets into the page in `_CLIENT_ASSETS` order (`watch.py:485`,
assembled at `watch.py:676-689`). The bundle must see the same files in the
same order, so the order is READ OUT of watch.py by AST
(`client_dist.asset_order`) — the same trick `dev/deploy_state.py:292-315`
uses on `DATA_SIBLINGS`. A second hand-written list would be a second truth,
and the first UI commit that reordered the page would have left it behind
silently.

**The builders are consumed, never copied.** The generated entry reads
`client/*.js` in place and appends `dev/build/wrapper-exports.js` into the
same lexical scope. There is no second checkout of the builders and no second
statement of any markup, so at the markup level there is nothing to diverge.
What CAN go wrong is staleness — dist compiled from yesterday's builders — and
that is what `manifest.json` and `client_dist.check` exist for.

Node is a dev-time dependency here, the same class as the browser guards
(`justfile:323`). It is never a serve-time one: `client/dist/` is committed,
`just deploy` ships committed state, and `watch.py` imports nothing outside
the stdlib.
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import client_dist  # noqa: E402  (after the path insert, deliberately)

ESBUILD = os.path.join(ROOT, "dev", "build", "node_modules", ".bin", "esbuild")
BUILD_DIR = os.path.join(ROOT, "dev", "build")
NODE_MODULES = os.path.join(BUILD_DIR, "node_modules")

BANNER = """\
/* GENERATED by `just build-client` (dev/build_client.py) — DO NOT EDIT.
 *
 * Built from client/*.js in watch.py's own _CLIENT_ASSETS order, plus
 * dev/build/wrapper-exports.js. Edit those; then rebuild. If you edit an
 * input without rebuilding, `python3 lint.py` goes ERROR and names the file:
 * client/dist/manifest.json records the sha256 of every input and output.
 */"""


class BuildError(Exception):
    """A refusal with the fix named. Never a traceback at the user."""


def _tool_versions():
    versions = {}
    for key, cmd in (("node", ["node", "--version"]),
                     ("esbuild", [ESBUILD, "--version"])):
        try:
            res = subprocess.run(cmd, capture_output=True, timeout=60)
        except (OSError, subprocess.SubprocessError) as exc:
            raise BuildError("cannot run %s: %s" % (cmd[0], exc))
        if res.returncode != 0:
            raise BuildError("%s exited %d: %s" % (
                cmd[0], res.returncode,
                res.stderr.decode("utf-8", "replace").strip()))
        versions[key] = res.stdout.decode().strip()
    # #630 P2: React is INSIDE native.js, so "which React is the dashboard
    # about to run" is otherwise a question you answer by grepping a minified
    # artifact. Recorded here so it is answerable from the committed tree.
    # Not a staleness input (`check` never compares `tool`) — a version that
    # moved without the bytes moving is impossible, and one that moved WITH
    # them is already caught by the output hashes.
    for key, pkg in (("react", "react"), ("react-dom", "react-dom")):
        path = os.path.join(NODE_MODULES, pkg, "package.json")
        try:
            with open(path, encoding="utf-8") as f:
                versions[key] = json.load(f).get("version")
        except (OSError, ValueError) as exc:
            raise BuildError(
                "cannot read %s's version from %s: %s — run `npm ci` in "
                "dev/build (or `just build-client`, which does it)"
                % (pkg, path, exc))
    return versions


def generate_entry(root, order):
    """The bundle's source text: the JS assets in the page's own order, then
    the one hand-written file.

    Only the `.js` assets go in — `style.css` and `app_body.html` are in the
    asset list but are not JavaScript. That filter is DERIVED from the name,
    not a second list to maintain: adding `foo.js` to `_CLIENT_ASSETS` puts it
    in the bundle, in the page's position, with no edit here.
    """
    parts = []
    for name in order:
        if not name.endswith(".js"):
            continue
        path = os.path.join(root, "client", name)
        with open(path, "rb") as f:
            raw = f.read()
        if not raw:
            # The same refusal `watch._read_client` makes, for the same
            # reason: an empty asset bundles to a valid, silent nothing.
            raise BuildError(
                "client/%s is empty — refusing to bundle around a blank "
                "asset (watch.py refuses to serve one for the same reason)"
                % name)
        parts.append(raw.decode("utf-8"))
    if not parts:
        raise BuildError(
            "watch._CLIENT_ASSETS names no .js file — the generated entry "
            "would be the hand-written half alone, which is not a bundle of "
            "anything")
    with open(os.path.join(root, client_dist.WRAPPER_EXPORTS_REL),
              encoding="utf-8") as f:
        parts.append(f.read())
    return "\n".join(parts)


def build_native(root):
    """Emit `client/dist/native.js` — React + the component registry.

    #630 P2. The second bundle, and it differs from the design bundle above in
    the one way that matters on a page: it does NOT concatenate `client/*.js`.
    The design bundle must contain the builders (its consumer is a tool with
    no dashboard); this one must not (its consumer IS the dashboard, which is
    already running them). Concatenating them here would re-run 40 top-level
    side effects — `setInterval(ages, 1e3)`, `document.addEventListener`,
    `window.dreambg = …` — a second time, against the same document. #653
    measured that count and flagged it; this is the phase that has to care.

    So the builders are referenced by bare name and resolved at render time
    from the page's own script scope. `test_client_dist` asserts their source
    text is ABSENT here, with the same probe asserted PRESENT in the design
    bundle so the detector cannot pass by looking for nothing.
    """
    entry_dir = os.path.join(root, client_dist.NATIVE_SRC_DIR)
    entry = os.path.basename(client_dist.NATIVE_ENTRY_REL)
    if not os.path.exists(os.path.join(entry_dir, entry)):
        raise BuildError(
            "%s does not exist — the native runtime has no entry point"
            % client_dist.NATIVE_ENTRY_REL)

    out = os.path.join(root, client_dist.NATIVE_REL)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    cmd = [
        ESBUILD, entry, "--bundle", "--format=iife",
        "--global-name=dwNative", "--target=es2020", "--charset=utf8",
        # React ships both builds behind this flag and picks at bundle time.
        # The DEV build is bigger, slower, and warns into a console nobody has
        # open; which React the dashboard runs is not an optimisation detail.
        #
        # THIS LINE LOOKS REDUNDANT AND IS NOT. esbuild already substitutes
        # `process.env.NODE_ENV` for a browser build — "production" when
        # minifying, "development" when not — so with `--minify` below, the
        # production build lands whether or not this flag is here. Measured:
        # deleting this line alone changes the artifact by zero bytes.
        #
        # What it defends against is deleting `--minify`, which is a change
        # someone will plausibly want (unminified diffs are readable). Also
        # measured, all three arms: define + minify = 146941 bytes,
        # production; define, no minify = 264646 bytes, still production; NO
        # define, no minify = 1066385 bytes, the DEVELOPMENT build. So without
        # this line, a formatting decision silently changes which React ships.
        # It is stated explicitly so that it cannot.
        '--define:process.env.NODE_ENV="production"',
        # Minified, because React dominates these bytes and nobody reads them;
        # `--line-limit` so an edit to one of OUR four source files still
        # produces a local diff rather than rewriting one enormous line. A
        # committed artifact whose every change is a whole-file diff is a
        # committed artifact nobody reviews.
        "--minify", "--line-limit=200",
        "--banner:js=" + BANNER,
        "--outfile=" + out,
    ]
    # Resolve `react` from the INVOKING repo's node_modules even when `root` is
    # a scratch clone that has none (the reproducibility test builds exactly
    # that). esbuild exposes this as `nodePaths` in its JS API and as NODE_PATH
    # on the CLI — there is no `--node-paths` flag, which is worth the comment
    # because the flag form fails as "Invalid build flag" and reads like a
    # version problem rather than a wrong-surface one.
    #
    # A fallback, not an override: in an ordinary build esbuild finds the same
    # directory by walking up from the entry, so both routes bundle the same
    # package and the artifact does not depend on which one won.
    env = dict(os.environ, NODE_PATH=NODE_MODULES)
    # `cwd=entry_dir` with a RELATIVE entry name, for #653's reason exactly:
    # esbuild can write the entry's path into the output, and a path that
    # varies by checkout location makes every rebuild emit different bytes —
    # manifest churn on a no-op rebuild, which is the false red that trains a
    # reader to ignore the true one.
    res = subprocess.run(cmd, cwd=entry_dir, env=env, capture_output=True,
                         timeout=300)
    if res.returncode != 0:
        raise BuildError("esbuild failed on the native runtime:\n%s"
                         % res.stderr.decode("utf-8", "replace").strip())
    return out


def build(root=ROOT):
    """Emit client/dist and return the manifest that was written."""
    if not os.path.exists(ESBUILD):
        raise BuildError(
            "esbuild is not installed. Run `npm ci` in dev/build (or `just "
            "build-client`, which does it). Serving never needs this — only "
            "changing what the build emits does.")

    order = client_dist.asset_order(root)
    if order is None:
        raise BuildError(
            "cannot read watch._CLIENT_ASSETS as a module-level literal — "
            "the bundle's asset order has no source")
    inputs = client_dist.expected_inputs(root)

    entry_src = generate_entry(root, order)

    ds_dir = os.path.join(root, client_dist.DS_DIR)
    os.makedirs(ds_dir, exist_ok=True)
    index_js = os.path.join(ds_dir, "index.js")

    with tempfile.TemporaryDirectory(prefix="dreamwork-build-") as tmp:
        # `.mjs`, so esbuild reads the entry as a module: the wrapper exports
        # are ESM and the whole entry shares one module scope, which is what
        # lets a wrapper name a builder lexically (#630 plan §2a).
        with open(os.path.join(tmp, "entry.mjs"), "w", encoding="utf-8") as f:
            f.write(entry_src)
        cmd = [ESBUILD, "entry.mjs", "--bundle", "--format=iife",
               "--global-name=DreamworkDesign", "--target=es2020",
               "--charset=utf8", "--banner:js=" + BANNER,
               "--outfile=" + index_js]
        # `cwd=tmp` and a RELATIVE entry name, because esbuild writes the
        # entry's path into the bundle as a comment. Measured, not assumed:
        # with an absolute path the two halves of a double build differed by
        # exactly that line and nothing else, so every rebuild would have
        # rewritten the committed artifact and its hash. A manifest that
        # churns on a no-op rebuild is a staleness signal nobody can read —
        # the false-red that trains you to ignore the check.
        res = subprocess.run(cmd, cwd=tmp, capture_output=True, timeout=300)
        if res.returncode != 0:
            raise BuildError("esbuild failed:\n%s" % res.stderr.decode(
                "utf-8", "replace").strip())

    # The design package ships the dashboard's own stylesheet, byte for byte —
    # a second copy that could be edited is a second authority for the visual
    # language, which is the thing Q1 refuses. `copyfile`, so the check that
    # they are byte-equal is checking a copy, not a transform.
    shutil.copyfile(os.path.join(root, "client", "style.css"),
                    os.path.join(ds_dir, "styles.css"))

    build_native(root)

    manifest = {
        "schema": client_dist.SCHEMA,
        # No timestamp, deliberately: a rebuild that changes nothing must
        # produce a byte-identical manifest, or `just build-client && git diff
        # --exit-code` cannot be used to ask whether dist is current.
        "tool": _tool_versions(),
        "asset_order": order,
        "inputs": {rel: client_dist.sha256_file(os.path.join(root, rel))
                   for rel in inputs},
        "outputs": {rel: client_dist.sha256_file(os.path.join(root, rel))
                    for rel in client_dist.OUTPUT_RELS},
    }
    unhashable = sorted(k for half in ("inputs", "outputs")
                        for k, v in manifest[half].items() if v is None)
    if unhashable:
        raise BuildError("could not hash %s — refusing to write a manifest "
                         "with holes in it" % ", ".join(unhashable))

    path = os.path.join(root, client_dist.MANIFEST_REL)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
        f.write("\n")
    return manifest


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--root", default=ROOT)
    args = ap.parse_args(argv)
    try:
        manifest = build(args.root)
    except BuildError as exc:
        print("build-client: %s" % exc, file=sys.stderr)
        return 1
    for rel, digest in sorted(manifest["outputs"].items()):
        size = os.path.getsize(os.path.join(args.root, rel))
        print("  %-30s %7d bytes  %s" % (rel, size, digest[:12]))
    print("  %-30s %7d inputs, tool %s" % (
        client_dist.MANIFEST_REL, len(manifest["inputs"]),
        manifest["tool"].get("esbuild")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
