"""#653 — `just build-client`: emit `client/dist/` from the tree, and record
exactly which tree it was.

This is P1 of the #630 component transition: the build step, emitting nothing
the page uses. The dashboard is byte-identical with and without it — that is
the whole claim of this phase, and it is checked in `test_client_dist.py`
rather than argued.

Two properties are built in here rather than left to care:

**The entry is GENERATED, never maintained.** `watch.py` concatenates the
client assets into the page in `_CLIENT_ASSETS` order (`watch.py:485`,
assembled at `watch.py:676-689`). The bundle must see the same files in the
same order, so the order is READ OUT of watch.py by AST
(`client_dist.asset_order`) — the same trick `dev/deploy_state.py:292-315`
uses on `DATA_SIBLINGS`. A second hand-written list would be a second truth,
and the first UI commit that reordered the page would have left it behind
silently.

**The builders are consumed, never copied.** The generated entry reads
`client/*.js` in place and appends `dev/build/wrapper-exports.js` into the
same lexical scope. There is no second checkout of the builders and no second
statement of any markup, so at the markup level there is nothing to diverge.
What CAN go wrong is staleness — dist compiled from yesterday's builders — and
that is what `manifest.json` and `client_dist.check` exist for.

Node is a dev-time dependency here, the same class as the browser guards
(`justfile:323`). It is never a serve-time one: `client/dist/` is committed,
`just deploy` ships committed state, and `watch.py` imports nothing outside
the stdlib.
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import client_dist  # noqa: E402  (after the path insert, deliberately)

ESBUILD = os.path.join(ROOT, "dev", "build", "node_modules", ".bin", "esbuild")
BUILD_DIR = os.path.join(ROOT, "dev", "build")

BANNER = """\
/* GENERATED by `just build-client` (dev/build_client.py) — DO NOT EDIT.
 *
 * Built from client/*.js in watch.py's own _CLIENT_ASSETS order, plus
 * dev/build/wrapper-exports.js. Edit those; then rebuild. If you edit an
 * input without rebuilding, `python3 lint.py` goes ERROR and names the file:
 * client/dist/manifest.json records the sha256 of every input and output.
 */"""


class BuildError(Exception):
    """A refusal with the fix named. Never a traceback at the user."""


def _tool_versions():
    versions = {}
    for key, cmd in (("node", ["node", "--version"]),
                     ("esbuild", [ESBUILD, "--version"])):
        try:
            res = subprocess.run(cmd, capture_output=True, timeout=60)
        except (OSError, subprocess.SubprocessError) as exc:
            raise BuildError("cannot run %s: %s" % (cmd[0], exc))
        if res.returncode != 0:
            raise BuildError("%s exited %d: %s" % (
                cmd[0], res.returncode,
                res.stderr.decode("utf-8", "replace").strip()))
        versions[key] = res.stdout.decode().strip()
    return versions


def generate_entry(root, order):
    """The bundle's source text: the JS assets in the page's own order, then
    the one hand-written file.

    Only the `.js` assets go in — `style.css` and `app_body.html` are in the
    asset list but are not JavaScript. That filter is DERIVED from the name,
    not a second list to maintain: adding `foo.js` to `_CLIENT_ASSETS` puts it
    in the bundle, in the page's position, with no edit here.
    """
    parts = []
    for name in order:
        if not name.endswith(".js"):
            continue
        path = os.path.join(root, "client", name)
        with open(path, "rb") as f:
            raw = f.read()
        if not raw:
            # The same refusal `watch._read_client` makes, for the same
            # reason: an empty asset bundles to a valid, silent nothing.
            raise BuildError(
                "client/%s is empty — refusing to bundle around a blank "
                "asset (watch.py refuses to serve one for the same reason)"
                % name)
        parts.append(raw.decode("utf-8"))
    if not parts:
        raise BuildError(
            "watch._CLIENT_ASSETS names no .js file — the generated entry "
            "would be the hand-written half alone, which is not a bundle of "
            "anything")
    with open(os.path.join(root, client_dist.WRAPPER_EXPORTS_REL),
              encoding="utf-8") as f:
        parts.append(f.read())
    return "\n".join(parts)


def build(root=ROOT):
    """Emit client/dist and return the manifest that was written."""
    if not os.path.exists(ESBUILD):
        raise BuildError(
            "esbuild is not installed. Run `npm ci` in dev/build (or `just "
            "build-client`, which does it). Serving never needs this — only "
            "changing what the build emits does.")

    order = client_dist.asset_order(root)
    if order is None:
        raise BuildError(
            "cannot read watch._CLIENT_ASSETS as a module-level literal — "
            "the bundle's asset order has no source")
    inputs = client_dist.expected_inputs(root)

    entry_src = generate_entry(root, order)

    ds_dir = os.path.join(root, client_dist.DS_DIR)
    os.makedirs(ds_dir, exist_ok=True)
    index_js = os.path.join(ds_dir, "index.js")

    with tempfile.TemporaryDirectory(prefix="dreamwork-build-") as tmp:
        # `.mjs`, so esbuild reads the entry as a module: the wrapper exports
        # are ESM and the whole entry shares one module scope, which is what
        # lets a wrapper name a builder lexically (#630 plan §2a).
        with open(os.path.join(tmp, "entry.mjs"), "w", encoding="utf-8") as f:
            f.write(entry_src)
        cmd = [ESBUILD, "entry.mjs", "--bundle", "--format=iife",
               "--global-name=DreamworkDesign", "--target=es2020",
               "--charset=utf8", "--banner:js=" + BANNER,
               "--outfile=" + index_js]
        # `cwd=tmp` and a RELATIVE entry name, because esbuild writes the
        # entry's path into the bundle as a comment. Measured, not assumed:
        # with an absolute path the two halves of a double build differed by
        # exactly that line and nothing else, so every rebuild would have
        # rewritten the committed artifact and its hash. A manifest that
        # churns on a no-op rebuild is a staleness signal nobody can read —
        # the false-red that trains you to ignore the check.
        res = subprocess.run(cmd, cwd=tmp, capture_output=True, timeout=300)
        if res.returncode != 0:
            raise BuildError("esbuild failed:\n%s" % res.stderr.decode(
                "utf-8", "replace").strip())

    # The design package ships the dashboard's own stylesheet, byte for byte —
    # a second copy that could be edited is a second authority for the visual
    # language, which is the thing Q1 refuses. `copyfile`, so the check that
    # they are byte-equal is checking a copy, not a transform.
    shutil.copyfile(os.path.join(root, "client", "style.css"),
                    os.path.join(ds_dir, "styles.css"))

    manifest = {
        "schema": client_dist.SCHEMA,
        # No timestamp, deliberately: a rebuild that changes nothing must
        # produce a byte-identical manifest, or `just build-client && git diff
        # --exit-code` cannot be used to ask whether dist is current.
        "tool": _tool_versions(),
        "asset_order": order,
        "inputs": {rel: client_dist.sha256_file(os.path.join(root, rel))
                   for rel in inputs},
        "outputs": {rel: client_dist.sha256_file(os.path.join(root, rel))
                    for rel in client_dist.OUTPUT_RELS},
    }
    unhashable = sorted(k for half in ("inputs", "outputs")
                        for k, v in manifest[half].items() if v is None)
    if unhashable:
        raise BuildError("could not hash %s — refusing to write a manifest "
                         "with holes in it" % ", ".join(unhashable))

    path = os.path.join(root, client_dist.MANIFEST_REL)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
        f.write("\n")
    return manifest


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--root", default=ROOT)
    args = ap.parse_args(argv)
    try:
        manifest = build(args.root)
    except BuildError as exc:
        print("build-client: %s" % exc, file=sys.stderr)
        return 1
    for rel, digest in sorted(manifest["outputs"].items()):
        size = os.path.getsize(os.path.join(args.root, rel))
        print("  %-30s %7d bytes  %s" % (rel, size, digest[:12]))
    print("  %-30s %7d inputs, tool %s" % (
        client_dist.MANIFEST_REL, len(manifest["inputs"]),
        manifest["tool"].get("esbuild")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
